# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: Sans
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Portfolio site of Ganga AS, Content Writer & Strategist'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: false
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: false

footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: ''
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: false
hugoblox:
  identity:
    name: Ganga AS
    organization: GenY Medium
    tagline: Copy Writer & Content Strategist | Driving Measurable Traffic Growth | B2B/B2C Content Expert
    description: I'm a results-driven Content & Copywriter with proven expertise in creating high-impact content and copy
  theme:
    pack: minimal
    colors:
      primary: gray
    mode: dark
  content:
    reading_time:
      enable: false
  layout:
    spacing: compact
